# Generated by Django 5.2.1 on 2025-06-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Book Name"
                    ),
                ),
                ("description", models.TextField()),
                ("rate", models.IntegerField(default=0)),
                ("views", models.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
